<a href="https://colab.research.google.com/github/Lio-Jung/Learning_ML/blob/main/ML_tf_%ED%95%99%EC%8A%B5%EC%9E%98%EB%90%98%EA%B2%8C%EB%AA%A8%EB%8D%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Batchnormalization

# 학습이 잘 되는 모델
* 사용할 레이어
  * tf.keras.layers.BatchNormalization()
  * tf.keras.layers.Activation('swish')
* 데이터
  * 보스턴 집값 예측: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv
  * 아이리스 품종 분류: "https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris2.csv"



In [1]:
#library
import pandas as pd
import tensorflow as tf

In [5]:
#read data
ref = "https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv"
boston = pd.read_csv(ref)
print(boston.columns)


Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


In [8]:
#slice data
ind_v = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
d_v = boston[['medv']]

#Hiddenlayer with Batchnormalization

In [22]:
#make model
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')
model.summary()


Model: "functional_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_11 (InputLayer)     │ (None, 13)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_23 (Dense)                │ (None, 8)              │           112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_15          │ (None, 8)              │            32 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_14 (Activation)      │ (None, 8)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_24 (Dense)                │ (None, 8)              │            72 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_16          │ (None, 8)              │            32 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_15 (Activation)      │ (None, 8)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_25 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 257 (1.00 KB)

 Trainable params: 225 (900.00 B)

 Non-trainable params: 32 (128.00 B)

In [23]:
model.fit(ind_v, d_v, epochs=100)

Epoch 1/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 595.5731
Epoch 2/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 573.3239 
Epoch 3/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 575.6422 
Epoch 4/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 559.2867 
Epoch 5/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 574.0206 
Epoch 6/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 567.1223 
Epoch 7/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 548.8459 
Epoch 8/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 555.9070 
Epoch 9/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 543.6379 
Epoch 10/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 564.4675 
Epoch 11/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 521.8398 
Epoch 12/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 511.6819 
Epoch 13/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 492.4534 
Epoch 14/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 527.9846 
Epoch 15/100
16/16 ━━━━━━━━━━━

same with Classification

In [44]:
#read data
ref = "https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris2.csv"
iris = pd.read_csv(ref)
print(iris.dtypes) # problem: '품종 is int64'. -> must be changed to category for onehotencoding
print(iris.isna().sum()) # problem: NaN data in data

꽃잎길이     float64
꽃잎폭      float64
꽃받침길이    float64
꽃받침폭     float64
품종         int64
dtype: object
꽃잎길이     0
꽃잎폭      1
꽃받침길이    0
꽃받침폭     0
품종       0
dtype: int64


In [62]:
#problem solve: change type
iris['품종'] = iris['품종'].astype('category')
print(iris.dtypes)
print(iris.dtypes)

꽃잎길이      float64
꽃잎폭       float64
꽃받침길이     float64
꽃받침폭      float64
품종       category
dtype: object
꽃잎길이      float64
꽃잎폭       float64
꽃받침길이     float64
꽃받침폭      float64
품종       category
dtype: object


In [63]:
#problem solve: put mean into NaN
mean = iris['꽃잎폭'].mean()
iris['꽃잎폭'] = iris['꽃잎폭'].fillna(mean)
print(iris.isna().sum())

꽃잎길이      float64
꽃잎폭       float64
꽃받침길이     float64
꽃받침폭      float64
품종       category
dtype: object
꽃잎길이     0
꽃잎폭      0
꽃받침길이    0
꽃받침폭     0
품종       0
dtype: int64
꽃잎길이      float64
꽃잎폭       float64
꽃받침길이     float64
꽃받침폭      float64
품종       category
dtype: object


In [69]:
#one hot encoding again
iris = pd.get_dummies(iris)
print(iris.columns)
iris.head()

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_0', '품종_1', '품종_2'], dtype='object')


꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_0   품종_1   품종_2
0   5.1  3.5    1.4   0.2  True  False  False
1   4.9  3.0    1.4   0.2  True  False  False
2   4.7  3.2    1.3   0.2  True  False  False
3   4.6  3.1    1.5   0.2  True  False  False
4   5.0  3.6    1.4   0.2  True  False  False

In [70]:
#variable
ind_v = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
d_v = iris[['품종_0', '품종_1', '품종_2']]

In [102]:
#model
X = tf.keras.layers.Input(shape=[4])

H = tf.keras.layers.Dense(5)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(5)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse', metrics=['accuracy'])
#model.summary()

In [103]:
#fit
model.fit(ind_v, d_v, epochs=100)

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.3406 - loss: 0.2153
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4016 - loss: 0.1991 
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4539 - loss: 0.1914 
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5790 - loss: 0.1808 
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6530 - loss: 0.1790 
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5457 - loss: 0.1755 
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6117 - loss: 0.1731 
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5344 - loss: 0.1795 
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5734 - loss: 0.1683 
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6740 - loss: 0.1551 
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6580 - loss: 0.1584 
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6678 - loss

In [104]:
#use
print(model.predict(ind_v[0:5]))
print(d_v[0:5])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step
[[0.9689132  0.02188862 0.00919828]
 [0.96065503 0.02870745 0.01063752]
 [0.97083956 0.02041237 0.00874809]
 [0.9430167  0.04454147 0.01244183]
 [0.9672627  0.02325525 0.00948198]]
   품종_0   품종_1   품종_2
0  True  False  False
1  True  False  False
2  True  False  False
3  True  False  False
4  True  False  False
